name: MedConnect
description: "Una aplicación móvil para gestionar citas médicas construida con Flutter."
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  emoji_picker_flutter: ^4.3.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  intl: any
  path: ^1.9.0
  pie_chart: ^5.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  syncfusion_flutter_charts: ^28.1.39
  table_calendar: ^3.1.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/perfil.png
  generate: true
