name: proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  path: ^1.9.0
  pie_chart: ^5.4.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  syncfusion_flutter_charts: ^28.1.39
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/perfil.png
